# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_history_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='year_formed',
            field=models.DateField(),
        ),
    ]
